### ISSUE TITLE
Problem with default currency and symbol with parse!

### ISSUE THREAD

**Issue by dawidof** [RubyMoney/monetize#161]
```irb
3.1.2 :032 > Monetize.assume_from_symbol = true
 => true
3.1.2 :033 > Monetize.parse!("100 zł")     <-- correct
 => #<Money fractional:10000 currency:PLN>
3.1.2 :034 > Monetize.parse!("100 zz")     <-- correct
 => #<Money fractional:10000 currency:USD>
3.1.2 :035 > Money.default_currency=nil
 => nil
3.1.2 :036 > Monetize.parse!("100 zł")     <-- not parsing
/Users/dmytro/.rvm/gems/ruby-3.1.2/gems/money-6.16.0/lib/money/currency.rb:40:in `new': Unknown currency '' (Money::Currency::UnknownCurrency)
3.1.2 :037 > Monetize.parse!("100 zz")     <-- correct
/Users/dmytro/.rvm/gems/ruby-3.1.2/gems/money-6.16.0/lib/money/currency.rb:40:in `new': Unknown currency '' (Money::Currency::UnknownCurrency)
3.1.2 :038 >
```

**Comment by rgalanakis** [comment]
Also running into this.
